name: Sync board from Google Sheet

on:
  workflow_dispatch:          # manual “Run workflow” button
  schedule:
    - cron: "0 6 * * *"       # every day at 06:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SHEET_CSV_URL:        ${{ secrets.SHEET_CSV_URL }}
      SHEET_TEAMS_CSV_URL:  ${{ secrets.SHEET_TEAMS_CSV_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --quiet --upgrade requests

      - name: Convert CSV → game-config.json
        run: python tools/csv_to_board.py
      - name: Commit & push
        run: |
         git config user.name  "sheet-bot"
         git config user.email "sheet-bot@users.noreply.github.com"
         git add game-config.json
         if git diff --cached --quiet; then
            echo "No changes"
         else
            git commit -m "auto: board update"
            git pull --rebase origin main      # <-- merge remote changes
            git push origin HEAD:main
         fi
